backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "live"
    label: "Live"
    files:
      - file: "content/live.yml"
        label: "Live Settings"
        name: "live"
        fields:
          - { label: "YouTube Link", name: "youtube_link", widget: "string" }
          - { label: "Facebook Link", name: "facebook_link", widget: "string" }
          - { label: "Is Live", name: "is_live", widget: "boolean" }
